// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Shaz_TileChangerMZ","status":true,"description":"Change tiles on map or copy tiles from another map","parameters":{}}
];
